### ISSUE TITLE
[Feat]: Document scheduler settings in admin guide

### ISSUE THREAD

**Issue by andaaron** [project-zot/project-zot.github.io#101]
### Is your feature request related to a problem? Please describe.

Update admin guide documentation to include the scheduler settings added in: https://github.com/project-zot/zot/commit/d4f200c2e15d74eb4d147d3286300ec1faad1ff9

### Describe alternatives you've considered

Just to be on the safe side @rchincha do we advertise this configuration to the users?

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/tree/main/examples#scheduler-workers

**Comment by mbshields** [comment]
I don't understand the concept of scheduler workers.  Can you explain further or point me to some explanation?  Thanks

**Comment by andaaron** [comment]
> I don't understand the concept of scheduler workers. Can you explain further or point me to some explanation? Thanks

There are various tasks which zot needs to run in the background at various times, in both the core code and in some extensions, for example the garbage collection logic or the zot copying remote images for the zot sync extension.
These tasks are queued and executed by the scheduler.

The scheduler itself can run a maximum number of tasks at the same time. The `numWorkers` setting which was added allows the user to configure the maximum number of tasks which can be run at the same time.
If `numWorkers` is not specified in the config, it defaults to the number of CPUs available to the zot process multiplied by 4. Most users should not need to modify this value.

**Comment by mbshields** [comment]
This information is added in the documentation PR #119

**Comment by andaaron** [comment]
This has been fixed in #119
