### ISSUE TITLE
[Feat]: Docs: clarify local authentication settings needed to encrypt passwords

### ISSUE THREAD

**Issue by andaaron** [project-zot/project-zot.github.io#102]
### Is your feature request related to a problem? Please describe.

One of the users reported:

If the base64 encoded user:password is provided, in determining the validity of the Basic Auth credentials, the [basicAuthHandler](https://github.com/project-zot/zot/blob/d78ef0b1bddcf5789d5ef410d64498b75ec342aa/pkg/api/authn.go#L242) function in authn.go, compares the bycrypt hash of the retrieved password with of password hash of the looked up username. However, while use of bycrypt by users, when encrypting passwords is sensible security, making such an assumption, without making it a documented requirement, isn't user friendly.

### Describe the solution you'd like

Maybe the user did not find the authentication document, but I think we should at least make the use of `bycrypt ` explicit in the text at https://zotregistry.io/v1.4.3/articles/authn-authz/#htpasswd

Right now it only mentions the `B` option in the command `htpasswd -bBn`, which may be too easy for the user to miss.

**Comment by rchincha** [comment]
PR #106 fixes this.
