### ISSUE TITLE
Update CLI related documentation

### ISSUE THREAD

**Issue by laurentiuNiculae** [project-zot/project-zot.github.io#123]
### Is your feature request related to a problem? Please describe.

The main commands of our ZLI have changed quite drastically and the documentation needs updates. 

A major change that affects all commands/subcommands is that now the config is not specified as an argument to the command but as the `--config` flag.
- zli images -n alpine my-zot-server
  &darr;
- zli image name alpine --config my-zot-server

The `--output`, `-o` flag has been changed to `--format`, `-f`

The old commands that used to be specified using flags have been moved into subcommands:

`zli images --base-images` &rarr; `zli image base`
`zli cve --cve-id --fixed` &rarr; `zli cve fixed`
`etc. `

I'll open a PR when I'll note how the new commands should look like for the [zli.md ](https://github.com/project-zot/project-zot.github.io/blob/main/docs/user-guides/zli.md)file.

I'll list the mapping from old to new here just in case. I've notated the arguments with square brakets: [repo]
## `images` &rarr; `image`
| Old | New |
|--------|--------|
| images --name, -n | image name |
| images --base-images, -b | image base | 
| images --derived-images, -D | image derived | 
| images --digest, -d | image digest|
| images | image list |

## `cve` &rarr; `cve`
| Old | New |
|--------|--------|
| cve  --cve-id | cve affected [cve-id] |
| cve --image | cve list [repo:tag] |
| cve --image --cve-id --fixed | cve fixed [repo] [cve-id] |
| cve --image --cve-id | cve list [repo:tag] --cve-id |
| cve --image --search | cve list [repo:tag] --cve-id |

## `search` &rarr; `search`
| Old | New |
|--------|--------|
| search --subject | search subject [repo:tag] |
| search --query | search query  [repo] |

## `repos` &rarr; `repo`
| Old | New |
|--------|--------|
| repos | repo list |

**Comment by andaaron** [comment]
Note sorting was also added in https://github.com/project-zot/zot/issues/1625
