### ISSUE TITLE
[Feat]: Document the retention policy configuration

### ISSUE THREAD

**Issue by andaaron** [project-zot/project-zot.github.io#129]
### Is your feature request related to a problem? Please describe.

Original issue: https://github.com/project-zot/zot/issues/1634
The PR in which the feature is implemented: https://github.com/project-zot/zot/pull/1866
More specifically this readme in the PR: https://github.com/project-zot/zot/pull/1866/files#diff-49aaa2819e35a856818ecec8c9fa7e1c79ad028d3f44bd749736353cfb51bac9

**Comment by andaaron** [comment]
Hi @mbshields, can we close this issue as completed?

**Comment by mbshields** [comment]
Article is published now.

**Comment by mbshields** [comment]
Yes, closed now.
