### ISSUE TITLE
[Feat]: List next or develop as tagged version in selectable

### ISSUE THREAD

**Issue by tonivj5** [project-zot/project-zot.github.io#139]
### Is your feature request related to a problem? Please describe.

It would be awesome to be able to select the latest docs from the select
![image](https://github.com/project-zot/project-zot.github.io/assets/7110786/b8f0c81d-8f2e-41af-8c9d-27100f82037e)

I want to try the latest release (2.0.0-rc7) but checking the new config or docs is a bit hard...

### Describe the solution you'd like

Add `next` / `develop` as a select option, like many other projecs do
![image](https://github.com/project-zot/project-zot.github.io/assets/7110786/3be6e815-7594-47b8-92d4-c86de28a3791)

**Comment by rchincha** [comment]
v2.0.0 is now released and docs have been updated.
