### ISSUE TITLE
[Bug]: zotregistry.io is down

### ISSUE THREAD

**Issue by dschier-wtd** [project-zot/project-zot.github.io#144]
### zot version

not relevant

### Describe the bug

The website under zotregistry.io is down.

### To reproduce

1. Open a browser
2. point to https://zotregistry.io

### Expected behavior

Website loads and documentation can be viewed

**Comment by ajsmiller** [comment]
This is worrying:


```
$ date;  whois zotregistry.io | head
Do 4. Jan 16:30:28 CET 2024
Domain Name: zotregistry.io
Registry Domain ID: dd1cc964ac71472d8d9ec5c4d77abe59-DONUTS
Registrar WHOIS Server: whois.1api.net
Registrar URL: http://www.1api.net
Updated Date: 2023-12-31T19:06:38Z
Creation Date: 2021-11-17T18:26:15Z
Registry Expiry Date: 2023-11-17T18:26:15Z
Registrar: 1API GmbH
Registrar IANA ID: 1387
Registrar Abuse Contact Email: abuse@1api.net
```

**Comment by ajsmiller** [comment]
I deleted my comment  with evidence of failure to renew earlier this morning CET, after considering the problems that this information might cause...

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/issues/2157

Yes, addressing this.

**Comment by rchincha** [comment]
https://zotregistry.dev/

If using helm,
helm repo add zot https://zotregistry.dev/helm-charts/

Between Google domains sale to Squarespace, renewal notice sent out during holidays, etc, [zotregistry.io](http://zotregistry.io/) has been parked. We are trying to revive it, however, going forward would move to https://zotregistry.dev/ - we have put in better control/process around this. Our sincerest apologies for this disruption 😞
