### ISSUE TITLE
[Bug]: Website Trademark disclaimer not linked appropriately

### ISSUE THREAD

**Issue by thisisobate** [project-zot/project-zot.github.io#152]
### zot version

None

### Describe the bug

The Linux Foundation trademark disclaimer contains a bug in the url. It links to `ihttps://www.linuxfoundation.org/trademark-usage/` instead of `https://www.linuxfoundation.org/trademark-usage/`.Foundation

### To reproduce

1. Go to https://zotregistry.dev/v2.0.1/
2. Head down to the footer of the page
3. Click the trademark disclaimer and see where it redirects you

### Expected behavior

Trademark should link to https://www.linuxfoundation.org/trademark-usage/

### Additional context

To fix, edit the trademark disclaimer, and remove the **i** prefixed before the trademark URL: https://www.linuxfoundation.org/trademark-usage/

**Comment by rchincha** [comment]
This is now fixed.
