### ISSUE TITLE
[Bug]: malware redirection from the home page

### ISSUE THREAD

**Issue by TwP** [project-zot/project-zot.github.io#166]
### zot version

current

### Describe the bug

Go to the current home page - https://zotregistry.dev/v2.0.2/ - and click on the "ecosystem tools" link. That URL references the `zotregistry.io` domain - https://zotregistry.io/latest/user-guides/user-guide-datapath/

The domain should be `zotregistry.dev`

**Comment by rchincha** [comment]
@TwP thanks for filing this, we will fix this.
