### ISSUE TITLE
[Bug]: Update in ORAS documentation

### ISSUE THREAD

**Issue by ADorigi** [project-zot/project-zot.github.io#177]
### zot version

NA

### Describe the bug

The documentation at [Attach a reference using ORAS](https://zotregistry.dev/v2.1.0/user-guides/user-guide-datapath/#attach-a-reference) seems outdated. 

### To reproduce

1. Create an artifact to attach as a reference in ZOT registry.
2. Use `oras push` command as described in [ZOT documentation here](https://zotregistry.dev/v2.1.0/user-guides/user-guide-datapath/#attach-a-reference)

### Expected behavior

The artifact should be available as a reference to the given subject.

### Screenshots

![image](https://github.com/user-attachments/assets/e6508ef9-7cd6-4850-93de-e6142ff97e60)

### Additional context

The ORAS push command given in the user documentation for ZOT is as follows:

```
oras push localhost:5000/hello-artifact \
  --artifact-type 'signature/example' \
  --subject localhost:5000/hello-artifact:v2 \
  ./signature.json:application/json
```

The `oras push` command no longer has the option `--subject`, as evident in [the ORAS documentation here](https://oras.land/docs/commands/oras_push). 

From what I understand, the `oras attach` command achieves exactly what the outdated documentation above needed. 

The new command should be as follows:

```
oras attach \
  --artifact-type signature/example \
  localhost:5000/hello-artifact:v2 \
  signature.json 
```

**Comment by ADorigi** [comment]
If acceptable, I am willing to create a pull request addressing this change in the documentation.

**Comment by andaaron** [comment]
Hi @ADorigi, thanks for filing this issue, please create the PR.
Looks like we had updated the tests (https://github.com/project-zot/zot/blob/main/test/blackbox/pushpull.bats#L148) but forgot about the documentation.
